-- Reading: texts the learner pastes in the Mini App (private: D1 only, never the public repo), and a difficulty rating
-- per read text that sets the level of the next "Текст дня".
CREATE TABLE own_text (
  n          INTEGER PRIMARY KEY AUTOINCREMENT,  -- text id: u-r-<n, 6 digits>
  lang       TEXT NOT NULL,
  title      TEXT NOT NULL,
  text       TEXT NOT NULL,
  source_url TEXT,
  questions  TEXT,                 -- JSON [{q, options, answer}], generated by the AI on first open
  created_at INTEGER NOT NULL
);

ALTER TABLE reading_done ADD COLUMN rating TEXT;  -- easy | ok | hard
